package com.schemagenie.model;

import com.schemagenie.dto.DatabaseType;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.Instant;

/**
 * Stores a full generation session: input description, chosen database type,
 * the raw LLM JSON, and every generated output artifact. This app's own data
 * (users, sessions, history) lives in MongoDB regardless of which database
 * the *generated* schema targets.
 */
@Document(collection = "generated_schemas")
public class GeneratedSchema {
    @Id
    private String sessionId; // UUID string, used directly as the Mongo _id

    private String description;
    private DatabaseType databaseType;
    private String rawJson;
    private String modelClasses;
    private String migrationScript;
    private String erDiagram;

    /** Null when the session was generated by a guest and never claimed. */
    @Indexed
    private String userId;

    private Instant createdAt = Instant.now();
    private Instant updatedAt = Instant.now();

    public GeneratedSchema() {}

    public String getSessionId() { return sessionId; }
    public void setSessionId(String sessionId) { this.sessionId = sessionId; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public DatabaseType getDatabaseType() { return databaseType; }
    public void setDatabaseType(DatabaseType databaseType) { this.databaseType = databaseType; }
    public String getRawJson() { return rawJson; }
    public void setRawJson(String rawJson) { this.rawJson = rawJson; }
    public String getModelClasses() { return modelClasses; }
    public void setModelClasses(String modelClasses) { this.modelClasses = modelClasses; }
    public String getMigrationScript() { return migrationScript; }
    public void setMigrationScript(String migrationScript) { this.migrationScript = migrationScript; }
    public String getErDiagram() { return erDiagram; }
    public void setErDiagram(String erDiagram) { this.erDiagram = erDiagram; }
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
